name: 'Release'

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 30
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/* dist/ || true
          cp README.org dist/ || true
          cd dist
          zip -r release-${{ matrix.target }}.zip ./*
          cd ..
      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/release-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
