name: 'Release'

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 30
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}

      # 编译并自动发布 Release（含二进制）
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.org"

      # 新增：把产物上传到 Actions Artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          # artifacts 区域的文件名，支持表达式来区分矩阵
          name: ${{ github.event.repository.name }}-${{ matrix.target }}
          # rust-build.action 会把压缩包生成在 dist/ 目录下
          path: |
            dist/*
          if-no-files-found: error
